# Generated by Django 4.2.1 on 2025-01-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0007_remove_movies_review_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actors',
            options={'verbose_name': 'Actor', 'verbose_name_plural': 'Actors'},
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name': 'Film', 'verbose_name_plural': 'Films'},
        ),
        migrations.AlterField(
            model_name='actors',
            name='actor_names',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='name'),
        ),
    ]
